---
title: "BBoPP Lagering Masterminds"
author: "JRB"
date: "`r Sys.Date()`"
output:
  html_document:
    theme:
      bg: "#484848"
      fg: "#FDF7F7"
      primary: "#484848"
      navbar-bg: "#2e4263"
      base_font:
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google:
          family: JetBrains Mono
          local: false
    vertical_layout: scroll
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = F)

library(ggplot2)
library(shiny)
library(viridis)
library(tidyverse)
library(hrbrthemes)
library(ggalt)
library(tm)
library(wordcloud)
library(wordcloud2)
library(rsconnect)

bbopp <- 
  read.csv(
    "/Users/jrb/Desktop/R/BBoPP_data.csv",
    row.names = NULL,
    sep = ","
  )

bbopp$beer_number <- as.factor(bbopp$beer_number)

bbopp <- bbopp %>%
  group_by(beer_number) %>%
  add_count(Aroma, name = "aroma_count") %>%
  add_count(Appearance, name = "appearance_count") %>%
  add_count(Flavor, name = "flavor_count") %>%
  add_count(Mouthfeel, name = "mouthfeel_count") %>%
  add_count(Overall, name = "overall_count") %>%
  mutate(mean_aroma = mean(Aroma,na.rm=TRUE), mean_appearance = mean(Appearance,na.rm=TRUE), mean_flavor = mean(Flavor,na.rm=TRUE), mean_mouthfeel = mean(Mouthfeel,na.rm=TRUE), mean_overall = mean(Overall,na.rm=TRUE), mean_lager_ale = mean(lager_ale, na.rm=T))
```

### All Beers {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
  geom_boxplot(aes(y = Aroma, color = Yeast), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  theme_ipsum(grid = F) +
  ylab("Aroma Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Aroma Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
# ggplot(bbopp, aes(x = beer_number, y = Appearance)) +
#   geom_boxplot(aes(fill = Yeast), color = "lightgrey") +
#   #geom_point(aes(fill = Yeast)) +
#   scale_fill_manual(values = c(
#     "#9ccc65",
#     "#66bb6a",
#     "#26a69a",
#     "#26c6da",
#     "#7e57c2",
#     "#ab47bc"
#   )) +
#   #facet_grid(Yeast~.) +
#   coord_cartesian(y = c(1,3)) +
# # ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
# #   geom_boxplot(aes(y = Appearance, color = Yeast), color = "lightgrey") +
# #   scale_fill_manual(values = c(
# #     "#9ccc65",
# #     "#66bb6a",
# #     "#26a69a",
# #     "#26c6da",
# #     "#7e57c2",
# #     "#ab47bc"
# #   )) +
#   theme_ipsum(grid = F) +
#   ylab("Appearance Score") +
#   xlab("Beer Number") +
#   labs(title = "Appearance") +
#   theme(
#     plot.background = element_rect(fill = "#484848"),
#     axis.text.x = element_text(
#       vjust = 1,
#       hjust = 1,
#       color = "#85C8CD"
#     ),
#     axis.text.y = element_text(color = "#85C8CD", size = 14),
#     legend.text = element_text(colour = "#85C8CD", size = 14),
#     legend.position = "right",
#     legend.title = element_text(color = "#85C8CD"),
#     axis.title.x = element_text(colour = "#85C8CD", size = 14),
#     axis.title.y = element_text(colour = "#85C8CD", size = 14),
#     title = element_text(
#       colour = "#85C8CD",
#       size = 16,
#       hjust = 0.5
#     )
#   )

ggplot(bbopp, mapping = aes(x = beer_number)) +
  geom_point(aes(y = Appearance, color = Yeast), size = bbopp$appearance_count * 1.5) +
  #geom_boxplot(aes(y = Appearance, color = Yeast)) +
  scale_colour_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  geom_point(
    aes(y = mean_appearance, fill = 'Mean Appearance'),
    color = "white",
    shape = 15,
    size = 5,
    stat = 'identity'
  ) +
  scale_fill_manual(name = '', values = 'skyblue') +
  theme_ipsum(grid = F) +
  ylab("Appearance Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Appearance Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )

```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
  geom_boxplot(aes(y = Flavor, color = Yeast), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  theme_ipsum(grid = F) +
  ylab("Flavo(u)r Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Flavo(u)r Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
# ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
#   geom_boxplot(aes(y = Mouthfeel, color = Yeast), color = "lightgrey") +
#   scale_fill_manual(values = c(
#     "#9ccc65",
#     "#66bb6a",
#     "#26a69a",
#     "#26c6da",
#     "#7e57c2",
#     "#ab47bc"
#   )) +
#   theme_ipsum(grid = F) +
#   ylab("Mouthfeel Score") +
#   xlab("Beer Number") +
#   labs(title = "Mouthfeel") +
#   theme(
#     plot.background = element_rect(fill = "#484848"),
#     axis.text.x = element_text(
#       vjust = 1,
#       hjust = 1,
#       color = "#85C8CD"
#     ),
#     axis.text.y = element_text(color = "#85C8CD", size = 14),
#     legend.text = element_text(colour = "#85C8CD", size = 14),
#     legend.position = "right",
#     legend.title = element_text(color = "#85C8CD"),
#     axis.title.x = element_text(colour = "#85C8CD", size = 14),
#     axis.title.y = element_text(colour = "#85C8CD", size = 14),
#     title = element_text(
#       colour = "#85C8CD",
#       size = 16,
#       hjust = 0.5
#     )
#   )

ggplot(bbopp, mapping = aes(x = beer_number)) +
  geom_point(aes(y = Mouthfeel, color = Yeast), size = bbopp$mouthfeel_count * 1.5) +
  scale_colour_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  geom_point(
    aes(y = mean_mouthfeel, fill = 'Mean Mouthfeel'),
    color = "white",
    shape = 15,
    size = 5,
    stat = 'identity'
  ) +
  scale_fill_manual(name = '', values = 'skyblue') +
  theme_ipsum(grid = F) +
  ylab("Mouthfeel Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Mouthfeel Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
  geom_boxplot(aes(y = Overall, color = Yeast), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  theme_ipsum(grid = F) +
  ylab("Overall Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Overall Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Yeast)) +
  geom_boxplot(aes(y = Total, color = Yeast), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  theme_ipsum(grid = F) +
  ylab("Total Score") +
  xlab("Beer Number") +
  labs(title = "Distribution of Total Score by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = Technique, fill = Technique)) +
  geom_violin(aes(y = lager_ale), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    #"#66bb6a",
   # "#26a69a",
    "#26c6da",
   # "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Lager",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 7,
    x = 1,
    label = "Ale",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Technique") +
  labs(title = "Distribution of Lager-to-Ale Scores by Technique") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )

ggplot(bbopp, aes(x = Technique, fill = Technique)) +
  geom_violin(aes(y = dry_crisp), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    #"#66bb6a",
   # "#26a69a",
    "#26c6da",
   # "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Dry",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 7,
    x = 1,
    label = "Crisp",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Technique") +
  labs(title = "Distribution of Dry-to-Crisp Scores by Technique") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )

# mean lager_ale by beer plotted against ferm temp
# ggplot(bbopp, aes(x = Fermentation_Temp, color = Technique)) +
#   geom_point(aes(y = mean_lager_ale), size = 4) +
#   scale_color_manual(values = c(
#     "#9ccc65",
#     #"#66bb6a",
#    # "#26a69a",
#     "#26c6da",
#    # "#7e57c2",
#     "#ab47bc"
#   )) +
#   theme_ipsum(grid = F) +
#   xlab("Temp") +
#   labs(title = "Lager-to-Ale Spectrum") +
#   theme(
#     plot.background = element_rect(fill = "#484848"),
#     axis.text.x = element_text(
#       vjust = 1,
#       hjust = 1,
#       color = "#85C8CD"
#     ),
#     axis.text.y = element_text(color = "#85C8CD", size = 14),
#     legend.text = element_text(colour = "#85C8CD", size = 14),
#     legend.position = "right",
#     legend.title = element_text(color = "#85C8CD"),
#     axis.title.x = element_text(colour = "#85C8CD", size = 14),
#     axis.title.y = element_text(colour = "#85C8CD", size = 14),
#     title = element_text(
#       colour = "#85C8CD",
#       size = 16,
#       hjust = 0.5
#     )
#   )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Technique)) +
  geom_boxplot(aes(y = lager_ale, color = Technique), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    #"#66bb6a",
   # "#26a69a",
    "#26c6da",
   # "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Lager",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 7,
    x = 1,
    label = "Ale",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Beer Number") +
  labs(title = "Distribution of Lager-to-Ale Scores by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )

ggplot(bbopp, aes(x = beer_number, fill = as.factor(Fermentation_Temp))) +
  geom_boxplot(aes(y = lager_ale, color = as.factor(Fermentation_Temp)), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Lager",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 7,
    x = 1,
    label = "Ale",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Beer Number") +
  labs(title = "Distribution of Lager-to-Ale Scores by Fermentation Tempreture") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
ggplot(bbopp, aes(x = beer_number, fill = Technique)) +
  geom_boxplot(aes(y = dry_crisp, color = Technique), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    #"#66bb6a",
   # "#26a69a",
    "#26c6da",
   # "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Dry",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 6,
    x = 1,
    label = "Crisp",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Beer Number") +
  labs(title = "Distribution of Dry-to-Crisp Scores by Beer Number & Actual Technnique") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )

ggplot(bbopp, aes(x = beer_number, fill = as.factor(Fermentation_Temp))) +
  geom_boxplot(aes(y = dry_crisp, color = as.factor(Fermentation_Temp)), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  geom_vline(
    xintercept = -1,
    lwd = .5,
    colour = "#6db1c8",
    alpha = .7
  ) +
  ggplot2::annotate(
    "text",
    x = 1,
    y = 0,
    label = "Dry",
    color = "#85C8CD"
  ) +
  ggplot2::annotate(
    "text",
    y = 6,
    x = 1,
    label = "Crisp",
    color = "#85C8CD"
  ) +
  theme_ipsum(grid = F) +
  xlab("Beer Number") +
  labs(title = "Distribution of Dry-to-Crisp Scores by Fermentation Tempreture & Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
#geom_point(aes(y = Aroma, color = Yeast), size = bbopp$appearance_count * 1.5) +
#   scale_colour_manual(values = c(
  
ggplot(bbopp, mapping = aes(x = beer_number)) +
  geom_point(
    aes(y = OG, color = "OG"),
    shape = 15,
    size = 5
    ) +
  geom_point(
    aes(y = FG, color = "FG"),
    shape = 15,
    size = 5
  ) +
  theme_ipsum(grid = F) +
  ylab("Specific Gravity") +
  xlab("Beer Number") +
  labs(title = "Specific Gravity by Beer Number") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "right",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 1 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer1 <- bbopp %>%
  filter(beer_number == 1) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer1 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))

toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
d <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = d,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer1, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 1 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 2 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer2 <- bbopp %>%
  filter(beer_number == 2) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer2 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
e <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = e,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer2, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 2 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 3 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer3 <- bbopp %>%
  filter(beer_number == 3) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer3 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
f <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = f,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer3, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 3 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 4 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer4 <- bbopp %>%
  filter(beer_number == 4) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer4 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
g <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = g,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer4, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 4 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 5 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer5 <- bbopp %>%
  filter(beer_number == 5) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer5 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
h <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = h,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer5, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 5 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 6 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer6 <- bbopp %>%
  filter(beer_number == 6) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer6 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
i <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = i,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer6, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 6 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```

## Beer 7 {.tabset} 

```{r, fig.width= 10, fig.height= 6, warning=FALSE, echo=FALSE}
bbopp$beer_number <- as.numeric(bbopp$beer_number)
beer7 <- bbopp %>%
  filter(beer_number == 7) %>%
  pivot_longer(cols = 2:6)

ov_colors <-
  c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )

word2 <- beer7 %>%
  pivot_longer(
    cols = Comments,
    names_to = "comments",
    values_to = "text",
    values_drop_na = T
  ) %>%
  drop_na()

# changed "Corpus" to "VCorpus"
docs <-
  tm::VCorpus(tm::VectorSource(word2$text), readerControl = list(language =
                                                                   "en"))
toSpace <-
  content_transformer(function (x , pattern)
    gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("en"))

# specify stopwords as a character vector
docs <-
  tm_map(
    docs,
    removeWords,
    c(
      "the",
      "and",
      "pur",
      "her",
      "his",
      "were",
      "she",
      "he",
      "him",
      "could",
      "which",
      "when",
      "did",
      "had",
      "went",
      "they",
      "any",
      "because",
      "all",
      "than",
      "ani",
      "also",
      "where",
      "been",
      "them",
      "than",
      "why",
      "only",
      "has",
      "very",
      "have",
      "through",
      "per",
      "does",
      "within",
      "stated",
      "get"
    )
  ) 

# Remove punctuation
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
j <- data.frame(word = names(v), freq = v)

set.seed(1234)

wordcloud2(data = j,
           backgroundColor = "#484848",
           color = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  ))

#########
ggplot(beer7, aes(color = name, fill = name)) +
  geom_boxplot(aes(x = name, y = value, color = name, fill = name), color = "lightgrey") +
  scale_fill_manual(values = c(
    "#9ccc65",
    "#66bb6a",
    "#26a69a",
    "#26c6da",
    "#7e57c2",
    "#ab47bc"
  )) +
  coord_flip() +
  theme_ipsum(grid = F) +
  ylab("Scores") +
  xlab("") +
  labs(title = "Beer 7 Scores") +
  theme(
    plot.background = element_rect(fill = "#484848"),
    axis.text.x = element_text(
      vjust = 1,
      hjust = 1,
      color = "#85C8CD"
    ),
    axis.text.y = element_text(color = "#85C8CD", size = 14),
    legend.text = element_text(colour = "#85C8CD", size = 14),
    legend.position = "none",
    legend.title = element_text(color = "#85C8CD"),
    axis.title.x = element_text(colour = "#85C8CD", size = 14),
    axis.title.y = element_text(colour = "#85C8CD", size = 14),
    title = element_text(
      colour = "#85C8CD",
      size = 16,
      hjust = 0.5
    )
  )
```